/* Generated By:JavaCC: Do not edit this line. CustomParserTreeConstants.java Version 4.1d1 */
public interface CustomParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTVOID = 1;
  public int JJTPATH = 2;
  public int JJTDIRORNODE = 3;
  public int JJTCOMMAND = 4;
  public int JJTCONDITION = 5;
  public int JJTELEMENTVALUES = 6;
  public int JJTSUBELEMENTVALUE = 7;
  public int JJTSUBCONDITION = 8;
  public int JJTKEY = 9;
  public int JJTVAL = 10;
  public int JJTASTERISK = 11;
  public int JJTCOMPARESIGN = 12;
  public int JJTANDOR = 13;
  public int JJTNEWELEMENT = 14;


  public String[] jjtNodeName = {
    "Start",
    "void",
    "Path",
    "DirOrNode",
    "Command",
    "Condition",
    "ElementValues",
    "SubElementValue",
    "SubCondition",
    "key",
    "val",
    "asterisk",
    "CompareSign",
    "AndOr",
    "NewElement",
  };
}
/* JavaCC - OriginalChecksum=22619e1ee50d5a24cd11e9b218baaf3f (do not edit this line) */
