/* Generated By:JavaCC: Do not edit this line. CustomParserTreeConstants.java Version 4.1d1 */
public interface CustomParserTreeConstants
{
  public int JJTVOID = 0;


  public String[] jjtNodeName = {
    "void",
  };
}
/* JavaCC - OriginalChecksum=a697990c5eb51465e0444e62d7d49454 (do not edit this line) */
