/* Generated By:JJTree&JavaCC: Do not edit this line. CustomParserConstants.java */

/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CustomParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EOL = 3;
  /** RegularExpression Id. */
  int CMD = 4;
  /** RegularExpression Id. */
  int DIR_OR_NODE = 5;
  /** RegularExpression Id. */
  int QUOTE = 6;
  /** RegularExpression Id. */
  int LETTER = 7;
  /** RegularExpression Id. */
  int DIGIT = 8;
  /** RegularExpression Id. */
  int DOT = 9;
  /** RegularExpression Id. */
  int WORD = 10;
  /** RegularExpression Id. */
  int PATH = 11;
  /** RegularExpression Id. */
  int ASTERISK = 12;
  /** RegularExpression Id. */
  int eq = 13;
  /** RegularExpression Id. */
  int neq = 14;
  /** RegularExpression Id. */
  int gt = 15;
  /** RegularExpression Id. */
  int lt = 16;
  /** RegularExpression Id. */
  int COMPARE = 17;
  /** RegularExpression Id. */
  int and = 18;
  /** RegularExpression Id. */
  int or = 19;
  /** RegularExpression Id. */
  int AND_OR = 20;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "<EOL>",
    "<CMD>",
    "<DIR_OR_NODE>",
    "<QUOTE>",
    "<LETTER>",
    "<DIGIT>",
    "\".\"",
    "<WORD>",
    "<PATH>",
    "\"*\"",
    "\"=\"",
    "\"!=\"",
    "\">\"",
    "\"<\"",
    "<COMPARE>",
    "\"&&\"",
    "\"||\"",
    "<AND_OR>",
    "\"$\"",
    "\"with value\"",
    "\"with values\"",
    "\"[\"",
    "\"]\"",
    "\",\"",
    "\"==\"",
    "\"!\"",
  };

}
