/* Generated By:JavaCC: Do not edit this line. CustomParserTreeConstants.java Version 4.1d1 */
public interface CustomParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTVOID = 1;
  public int JJTPATH = 2;
  public int JJTDIRORNODE = 3;
  public int JJTCOMMAND = 4;
  public int JJTCONDITION = 5;
  public int JJTSUBCONDITION = 6;
  public int JJTKEY = 7;
  public int JJTVAL = 8;
  public int JJTCOMPARESIGN = 9;
  public int JJTANDOR = 10;
  public int JJTNEWELEMENT = 11;


  public String[] jjtNodeName = {
    "Start",
    "void",
    "Path",
    "DirOrNode",
    "Command",
    "Condition",
    "SubCondition",
    "key",
    "val",
    "CompareSign",
    "AndOr",
    "NewElement",
  };
}
/* JavaCC - OriginalChecksum=727a14c83839146317bdac5da75fa349 (do not edit this line) */
