/* Generated By:JJTree&JavaCC: Do not edit this line. CustomParserConstants.java */

/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CustomParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EOL = 3;
  /** RegularExpression Id. */
  int CMD = 4;
  /** RegularExpression Id. */
  int DIR_OR_NODE = 5;
  /** RegularExpression Id. */
  int LETTER = 6;
  /** RegularExpression Id. */
  int DOT = 7;
  /** RegularExpression Id. */
  int WORD = 8;
  /** RegularExpression Id. */
  int PATH = 9;
  /** RegularExpression Id. */
  int eq = 10;
  /** RegularExpression Id. */
  int gt = 11;
  /** RegularExpression Id. */
  int lt = 12;
  /** RegularExpression Id. */
  int COMPARE = 13;
  /** RegularExpression Id. */
  int and = 14;
  /** RegularExpression Id. */
  int or = 15;
  /** RegularExpression Id. */
  int AND_OR = 16;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "<EOL>",
    "<CMD>",
    "<DIR_OR_NODE>",
    "<LETTER>",
    "\".\"",
    "<WORD>",
    "<PATH>",
    "\"=\"",
    "\">\"",
    "\"<\"",
    "<COMPARE>",
    "\" & \"",
    "\" | \"",
    "<AND_OR>",
    "\"[\"",
    "\"]\"",
    "\"!\"",
  };

}
