/* Generated By:JJTree&JavaCC: Do not edit this line. CustomParser.java */
import java.io.FileNotFoundException;
import java.util.*;

public class CustomParser/*@bgen(jjtree)*/implements CustomParserTreeConstants, CustomParserConstants {/*@bgen(jjtree)*/
  protected static JJTCustomParserState jjtree = new JJTCustomParserState();public static void main(String[] args) {
       CustomParser customParser = null;
       if (args.length < 1) {
           customParser = new CustomParser(System.in);
       } else {
           try {
                customParser = new CustomParser(new java.io.DataInputStream(new java.io.FileInputStream(args[0])));
           } catch(FileNotFoundException e) {
                customParser = new CustomParser(System.in);
           }
       }
       try {
           ASTStart root = customParser.Start();
//           root.dump("");
           JsonDTO jsonDTO = new JsonDTO();
           ElementDTO elementDTO = null;
           List paths = new ArrayList();
           com.google.gson.Gson gson = new com.google.gson.Gson();
           for(int i = 0; i < root.jjtGetNumChildren(); i++) {
               String currentPath = "";
               Node current = root.jjtGetChild(i);
                   if (current.toString().contains(":")) {
                       String[] split = current.toString().split(":");
                       switch (split[0]) {
                              case "Command" : {
                                  jsonDTO.setCmd(split[1].trim());
                                  break;
                              }
                              case "Param" : {
                                  jsonDTO.setParam(split[1].trim());
                                  break;
                              }
                              case "Path" : {
                                  currentPath = split[1].trim().substring(1);
                                  break;
                              }
                              case "New element key" : {
                                  elementDTO = new ElementDTO();
                                  elementDTO.setElementKey(split[1].trim());
                                  break;
                              }
                              case "New element": {
                                  if (current.jjtGetChild(0).jjtGetNumChildren() > 0) {
                                      if (elementDTO == null) elementDTO = new ElementDTO();
                                      List values = new ArrayList();
                                      for (int h = 0; h < current.jjtGetNumChildren() ; h++) {
                                          ElementInitValuesDTO valuesDTO = new ElementInitValuesDTO();
                                          for(int g = 0; g < current.jjtGetChild(h).jjtGetNumChildren() ; g++) {
                                              Node elementLeaf = current.jjtGetChild(h).jjtGetChild(g);
                                               if (elementLeaf.toString().contains(":")) {
                                                   String[] split_ = elementLeaf.toString().split(":");
                                                   switch (split_[0]) {
                                                       case "key" : {
                                                           valuesDTO.setInit_value_key(split_[1].trim());
                                                           break;
                                                       }
                                                       case "value" : {
                                                           String utfval = split_[1].trim();
                                                           try {
                                                               Integer intval = Integer.parseInt(utfval);
                                                               valuesDTO.setInt_value(intval);
                                                           } catch (Exception e) {
                                                               valuesDTO.setUtf_value(utfval);
                                                           }
                                                       }
                                                   }
                                               }
                                            }
                                            values.add(valuesDTO);
                                      }

                                      elementDTO.setElement_init_values(values);
                                      elementDTO.setInit_values_n(values.size());
                                  }
                                  break;
                              }
                          }
                   }
                       ArrayList conds = null;
                       ArrayList operators = null;
                   if (current.jjtGetNumChildren() > 0) {
                       operators = new ArrayList();
                       conds = new ArrayList();
                       String and_or = "";
                   for(int j = 0; j < current.jjtGetNumChildren(); j++) {
                       Node subCurrent = current.jjtGetChild(j);
                         if ("and_or".equals(subCurrent.toString().split(":")[0])) {
                                                         and_or = subCurrent.toString().split(":")[1].trim();
                                                         operators.add("&&".equals(and_or) ? 1 : 0);
                                                  }
                       if (subCurrent.jjtGetNumChildren() > 0) {
                          SubCondDTO subCondDTO = new SubCondDTO();
                           for(int k = 0; k < subCurrent.jjtGetNumChildren(); k++) {
                               Node subSubCurrent = subCurrent.jjtGetChild(k);
                                if (subSubCurrent.toString().contains(":")) {
                                  String[] split = subSubCurrent.toString().split(":");
                                  switch (split[0]) {
                                     case "key" : {
                                         subCondDTO.setKey(split[1].trim());
                                         break;
                                      }
                                     case "value" : {
                                         String val = split[1].trim();
                                         try {
                                             int intval = Integer.parseInt(val);
                                             subCondDTO.setInt_value(intval);
                                         } catch (Exception e) {
                                             subCondDTO.setUtf_value(val);
                                         }
                                         break;
                                     }
                                     case "Sign": {
                                         subCondDTO.setSign(split[1].trim());
                                         break;
                                     }
                                     case "asterisk": {
                                         currentPath = split[1].trim();
                                         break;
                                     }
                                  }
                              }
                           }
                                conds.add(subCondDTO);
                       }
                   }
               }
                   if (!"".equals(currentPath)) {
                       switch (jsonDTO.getCmd()) {
                       case "delete": {
                         if (conds == null)
                             jsonDTO.append(new PathDTO(currentPath));
                         else if ("*".equals(currentPath))
                            jsonDTO.append(new PathDTO(currentPath));
                         else
                            jsonDTO.append(new PathDTO(currentPath, conds, operators, conds.size()));
                         break;
                       }
                       case "update":
                       case "create":   {
                           jsonDTO.append(new PathDTO(currentPath));
                            break;
                       }
                       case "read": {
                           if ((currentPath+".").equals("..")) {
                                   jsonDTO.setFrom_root(0);
                           } else
                            if (currentPath.contains(".")) {
                                for (String s : currentPath.split("\\."))
                                    jsonDTO.append(new PathDTO(s));
                              } else if (conds == null)
                                  jsonDTO.append(new PathDTO(currentPath));
                              else if ("*".equals(currentPath))
                                 jsonDTO.append(new PathDTO(currentPath));
                              else
                                 jsonDTO.append(new PathDTO(currentPath, conds, operators, conds.size()));
                              break;
                           }
                       }
                   }
       }
           jsonDTO.setNelem(elementDTO);
           jsonDTO.setPaths_n(jsonDTO.getPaths()!= null ? jsonDTO.getPaths().size() : null);
           String json = gson.toJson(jsonDTO);
           System.out.println(json);
       } catch (Exception e) {
           System.out.print("\t[-] Wrong input\n>\t");
//           System.out.println(e.getMessage());
       }

    }

  static final public ASTStart Start() throws ParseException {
                           /*@bgen(jjtree) Start */
  ASTStart jjtn000 = new ASTStart(JJTSTART);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      Input();
      jj_consume_token(EOL);
    jjtree.closeNodeScope(jjtn000, true);
    jjtc000 = false;
    {if (true) return jjtn000;}
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
    throw new Error("Missing return statement in function");
  }

  static final public void Input() throws ParseException {
    Command();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case DIR_OR_NODE:
      DirOrNode();
      break;
    default:
      jj_la1[0] = jj_gen;
      ;
    }
    jj_consume_token(21);
    label_1:
    while (true) {
      FullPath();
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case PATH:
        ;
        break;
      default:
        jj_la1[1] = jj_gen;
        break label_1;
      }
    }
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 28:
      NewElement();
      break;
    default:
      jj_la1[2] = jj_gen;
      ;
    }
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 22:
    case 23:
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 22:
        jj_consume_token(22);
        break;
      case 23:
        jj_consume_token(23);
        break;
      default:
        jj_la1[3] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      jj_consume_token(24);
      ElementValues();
      jj_consume_token(25);
      break;
    default:
      jj_la1[4] = jj_gen;
      ;
    }
  }

  static final public void FullPath() throws ParseException {
                        /*@bgen(jjtree) Path */
                        ASTPath jjtn000 = new ASTPath(JJTPATH);
                        boolean jjtc000 = true;
                        jjtree.openNodeScope(jjtn000);Token t;
    try {
      t = jj_consume_token(PATH);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 24:
        jj_consume_token(24);
        SubCondition();
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case ASTERISK:
        case AND_OR:
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case AND_OR:
            label_2:
            while (true) {
              AndOr();
              SubCondition();
              switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
              case AND_OR:
                ;
                break;
              default:
                jj_la1[5] = jj_gen;
                break label_2;
              }
            }
            break;
          case ASTERISK:
            jj_consume_token(ASTERISK);
            break;
          default:
            jj_la1[6] = jj_gen;
            jj_consume_token(-1);
            throw new ParseException();
          }
          break;
        default:
          jj_la1[7] = jj_gen;
          ;
        }
        jj_consume_token(25);
        break;
      default:
        jj_la1[8] = jj_gen;
        ;
      }
                                                                         jjtree.closeNodeScope(jjtn000, true);
                                                                         jjtc000 = false;
                                                                        jjtn000.setName(t.image);
    } catch (Throwable jjte000) {
      if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
      if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
  }

  static final public void DirOrNode() throws ParseException {
                               /*@bgen(jjtree) DirOrNode */
                               ASTDirOrNode jjtn000 = new ASTDirOrNode(JJTDIRORNODE);
                               boolean jjtc000 = true;
                               jjtree.openNodeScope(jjtn000);Token t;
    try {
      t = jj_consume_token(DIR_OR_NODE);
                      jjtree.closeNodeScope(jjtn000, true);
                      jjtc000 = false;
                     jjtn000.setName(t.image);
    } finally {
      if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
  }

  static final public void Command() throws ParseException {
                           /*@bgen(jjtree) Command */
                           ASTCommand jjtn000 = new ASTCommand(JJTCOMMAND);
                           boolean jjtc000 = true;
                           jjtree.openNodeScope(jjtn000);Token t;
    try {
      t = jj_consume_token(CMD);
              jjtree.closeNodeScope(jjtn000, true);
              jjtc000 = false;
             jjtn000.setName(t.image);
    } finally {
      if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
  }

  static final public void Condition() throws ParseException {
                               /*@bgen(jjtree) Condition */
  ASTCondition jjtn000 = new ASTCondition(JJTCONDITION);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      SubCondition();
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case AND_OR:
        label_3:
        while (true) {
          AndOr();
          SubCondition();
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case AND_OR:
            ;
            break;
          default:
            jj_la1[9] = jj_gen;
            break label_3;
          }
        }
        break;
      default:
        jj_la1[10] = jj_gen;
        ;
      }
    } catch (Throwable jjte000) {
      if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
      if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
  }

  static final public void ElementValues() throws ParseException {
                                       /*@bgen(jjtree) ElementValues */
  ASTElementValues jjtn000 = new ASTElementValues(JJTELEMENTVALUES);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      SubElementValue();
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 26:
        label_4:
        while (true) {
          jj_consume_token(26);
          SubElementValue();
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case 26:
            ;
            break;
          default:
            jj_la1[11] = jj_gen;
            break label_4;
          }
        }
        break;
      default:
        jj_la1[12] = jj_gen;
        ;
      }
    } catch (Throwable jjte000) {
      if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
      if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
  }

  static final public void SubElementValue() throws ParseException {
                                           /*@bgen(jjtree) SubElementValue */
  ASTSubElementValue jjtn000 = new ASTSubElementValue(JJTSUBELEMENTVALUE);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      key();
      jj_consume_token(27);
      val();
    } catch (Throwable jjte000) {
      if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
      if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
  }

  static final public void SubCondition() throws ParseException {
                                     /*@bgen(jjtree) SubCondition */
  ASTSubCondition jjtn000 = new ASTSubCondition(JJTSUBCONDITION);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case WORD:
        key();
        CompareSign();
        val();
        break;
      case ASTERISK:
        asterisk();
        break;
      default:
        jj_la1[13] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } catch (Throwable jjte000) {
      if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
      if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
  }

  static final public void key() throws ParseException {
                   /*@bgen(jjtree) key */
                   ASTkey jjtn000 = new ASTkey(JJTKEY);
                   boolean jjtc000 = true;
                   jjtree.openNodeScope(jjtn000);Token t;
    try {
      t = jj_consume_token(WORD);
               jjtree.closeNodeScope(jjtn000, true);
               jjtc000 = false;
              jjtn000.setName(t.image);
    } finally {
      if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
  }

  static final public void val() throws ParseException {
                   /*@bgen(jjtree) val */
                   ASTval jjtn000 = new ASTval(JJTVAL);
                   boolean jjtc000 = true;
                   jjtree.openNodeScope(jjtn000);Token t;
    try {
      t = jj_consume_token(WORD);
               jjtree.closeNodeScope(jjtn000, true);
               jjtc000 = false;
              jjtn000.setName(t.image);
    } finally {
      if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
  }

  static final public void asterisk() throws ParseException {
                             /*@bgen(jjtree) asterisk */
                             ASTasterisk jjtn000 = new ASTasterisk(JJTASTERISK);
                             boolean jjtc000 = true;
                             jjtree.openNodeScope(jjtn000);Token t;
    try {
      t = jj_consume_token(ASTERISK);
                   jjtree.closeNodeScope(jjtn000, true);
                   jjtc000 = false;
                  jjtn000.setName(t.image);
    } finally {
      if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
  }

  static final public void CompareSign() throws ParseException {
                                   /*@bgen(jjtree) CompareSign */
                                   ASTCompareSign jjtn000 = new ASTCompareSign(JJTCOMPARESIGN);
                                   boolean jjtc000 = true;
                                   jjtree.openNodeScope(jjtn000);Token t;
    try {
      t = jj_consume_token(COMPARE);
                  jjtree.closeNodeScope(jjtn000, true);
                  jjtc000 = false;
                 jjtn000.setName(t.image);
    } finally {
      if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
  }

  static final public void AndOr() throws ParseException {
                       /*@bgen(jjtree) AndOr */
                       ASTAndOr jjtn000 = new ASTAndOr(JJTANDOR);
                       boolean jjtc000 = true;
                       jjtree.openNodeScope(jjtn000);Token t;
    try {
      t = jj_consume_token(AND_OR);
                 jjtree.closeNodeScope(jjtn000, true);
                 jjtc000 = false;
                jjtn000.setName(t.image);
    } finally {
      if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
  }

  static final public void NewElement() throws ParseException {
                                 /*@bgen(jjtree) NewElement */
                                 ASTNewElement jjtn000 = new ASTNewElement(JJTNEWELEMENT);
                                 boolean jjtc000 = true;
                                 jjtree.openNodeScope(jjtn000);Token t;
    try {
      t = jj_consume_token(28);
      jj_consume_token(WORD);
                  jjtree.closeNodeScope(jjtn000, true);
                  jjtc000 = false;
                 jjtn000.setName(t.next.image);
    } finally {
      if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
  }

  static private boolean jj_initialized_once = false;
  /** Generated Token Manager. */
  static public CustomParserTokenManager token_source;
  static SimpleCharStream jj_input_stream;
  /** Current token. */
  static public Token token;
  /** Next token. */
  static public Token jj_nt;
  static private int jj_ntk;
  static private int jj_gen;
  static final private int[] jj_la1 = new int[14];
  static private int[] jj_la1_0;
  static {
      jj_la1_init_0();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0x20,0x800,0x10000000,0xc00000,0xc00000,0x100000,0x101000,0x101000,0x1000000,0x100000,0x100000,0x4000000,0x4000000,0x1400,};
   }

  /** Constructor with InputStream. */
  public CustomParser(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public CustomParser(java.io.InputStream stream, String encoding) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser.  ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new CustomParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 14; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jjtree.reset();
    jj_gen = 0;
    for (int i = 0; i < 14; i++) jj_la1[i] = -1;
  }

  /** Constructor. */
  public CustomParser(java.io.Reader stream) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser. ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new CustomParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 14; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  static public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jjtree.reset();
    jj_gen = 0;
    for (int i = 0; i < 14; i++) jj_la1[i] = -1;
  }

  /** Constructor with generated Token Manager. */
  public CustomParser(CustomParserTokenManager tm) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser. ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 14; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(CustomParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jjtree.reset();
    jj_gen = 0;
    for (int i = 0; i < 14; i++) jj_la1[i] = -1;
  }

  static private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }


/** Get the next Token. */
  static final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  static final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  static private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  static private java.util.List jj_expentries = new java.util.ArrayList();
  static private int[] jj_expentry;
  static private int jj_kind = -1;

  /** Generate ParseException. */
  static public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[29];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 14; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 29; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = (int[])jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  static final public void enable_tracing() {
  }

  /** Disable tracing. */
  static final public void disable_tracing() {
  }

}
